name: fpx
description: Lightweight Widget focused Mason brick cli
version: 0.0.2
homepage: https://github.com/jdde
repository: https://github.com/jdde/fpx
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason: ^0.1.0-dev.52
  mason_logger: ^0.3.3
  path: ^1.9.0
  pub_updater: ^0.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.6.0
  build_verify: ^3.1.0
  build_version: ^2.1.2
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^6.0.0

executables:
  fpx:
