name: fpx
description: Lightweight Widget focused Mason brick cli
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason: ^0.1.0-dev.52
  mason_logger: ^0.3.0
  path: ^1.9.0
  pub_updater: ^0.4.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  fpx:
