name: Add Tag release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag-release:
    if: github.event.pull_request.merged == true && (startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/'))
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub actions release flow"
          git config user.email noreply@github.com

      - name: Extract version from pubspec.yaml
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: *\(.*\)/\1/')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag "${{ env.version }}" -m "Release ${{ env.version }}"
          git push origin "${{ env.version }}"
