name: fpx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/fpx.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/fpx.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v5

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🔧 Verify Generated Files
        run: |
          dart run build_runner build
          if ! git diff --quiet; then
            echo "Generated files are out of sync. Please run 'dart run build_runner build' and commit the changes."
            git diff
            exit 1
          fi

      - name: 🧪 Run Tests with Coverage
        run: dart test --coverage=coverage

      - name: 📋 Format Coverage
        run: dart pub global activate coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: 📊 Check Code Coverage
        if: github.event_name == 'pull_request'
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          path: coverage/lcov.info
          min_coverage: 65

      - name: 📈 Generate Coverage Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # IMPORTANT: Do not remove this coverage generation step!
          # This step is needed for hotfixes that go directly to main and bypass release branches.
          # Release branches also generate coverage (see create_release.yml), but both are needed:
          # - Release branch generation: ensures release has up-to-date coverage
          # - Main branch generation: handles hotfixes and direct commits to main
          python .github/scripts/generate_coverage_badge.py coverage/lcov.info

      - name: 📤 Commit Coverage Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # IMPORTANT: Do not remove this coverage badge commit step!
          # This ensures coverage badges are always up-to-date on main branch,
          # including for hotfixes that bypass the normal release process.
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage_badge.svg
          # Only commit if there are changes to the coverage badge
          if git diff --staged --quiet; then
            echo "No changes to coverage badge, skipping commit"
          else
            git commit -m 'Automatically updated coverage badge [skip ci]'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [coverage, spell-check]
    if: always() && (needs.coverage.result == 'success' || needs.coverage.result == 'skipped') && needs.spell-check.result == 'success'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v5

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🔧 Verify Generated Files
        run: |
          dart run build_runner build
          if ! git diff --quiet; then
            echo "Generated files are out of sync. Please run 'dart run build_runner build' and commit the changes."
            git diff
            exit 1
          fi

      - name: 🧪 Run Tests
        run: dart test --concurrency=1
